import { StopETA } from "./types";

export const SingleETA: StopETA = {
    "co": "KMB",
    "data_timestamp": "",
    "dest_en": "Loading...",
    "dest_sc": "Loading...",
    "dest_tc": "Loading...",
    "dir" : "I",
    "eta": "Loading...",
    "eta_seq": 1,
    "rmk_en": "",
    "rmk_sc": "",
    "rmk_tc": "",
    "route": "2A",
    "seq": 10,
    "service_type": "1",
    "stop": "000001",
    "name_tc": "加載中...",
    "name_en": "Loading...",
    "name_sc": "加載中...",
}

export const ETALoading: StopETA[] = [
    {
        "co": "KMB",
        "data_timestamp": "2025-11-24T06:15:19+08:00",
        "dest_en": "Loading...",
        "dest_sc": "Loading...",
        "dest_tc": "Loading...",
        "dir" : "I",
        "eta": "Loading...",
        "eta_seq": 1,
        "rmk_en": "",
        "rmk_sc": "",
        "rmk_tc": "",
        "route": "2A",
        "seq": 10,
        "service_type": "1",
        "stop": "000001",
        "name_tc": "加載中...",
        "name_en": "Loading...",
        "name_sc": "加載中...",
    },
    {
        "co": "KMB",
        "data_timestamp": "2025-11-24T06:15:19+08:00",
        "dest_en": "Loading...",
        "dest_sc": "Loading...",
        "dest_tc": "Loading...",
        "dir" : "I",
        "eta": "Loading...",
        "eta_seq": 1,
        "rmk_en": "",
        "rmk_sc": "",
        "rmk_tc": "",
        "route": "2A",
        "seq": 10,
        "service_type": "1",
        "stop": "000001",
        "name_tc": "加載中...",
        "name_en": "Loading...",
        "name_sc": "加載中...",
    },
    {
        "co": "KMB",
        "data_timestamp": "2025-11-24T06:15:19+08:00",
        "dest_en": "Loading...",
        "dest_sc": "Loading...",
        "dest_tc": "Loading...",
        "dir" : "I",
        "eta": "Loading...",
        "eta_seq": 1,
        "rmk_en": "",
        "rmk_sc": "",
        "rmk_tc": "",
        "route": "2A",
        "seq": 10,
        "service_type": "1",
        "stop": "000001",
        "name_tc": "加載中...",
        "name_en": "Loading...",
        "name_sc": "加載中...",
    }
]